### ISSUE TITLE
Problem when using with JSPM/SystemJS

### ISSUE THREAD

**Issue by fusionstrings** [loklaan/react-redux-kit#1]
I am getting following error when using with JSPM/SystemJs

``` js
    Uncaught (in promise) Error: createReducers is not defined
```

when using https://github.com/loklaan/react-redux-kit/blob/master/src/reducers/github.js#L7-L9

``` js
export default createReducers(initialState, {
  [YOUR_CONSTANT]: (state, payload) => ({
    json: payload.data
  })
});
```

After converting it to classic action creator it works fine

``` js
export default function (state=initialState, payload){
  switch(payload.type){
    case YOUR_CONSTANT:
      return Object.assign({}, state, {json: payload.data})
    default:
      return state
  }
}
```

Although I would love to use this utility function.

**Comment by loklaan** [comment]
Hi mate, I'd recommend trying the original kit, https://github.com/davezuko/react-redux-starter-kit. It may solve your issue.

I don't actively maintain the current version of this boiler plate that I've hastily forked.

The fork happened for the above repo after I decided I had to make quite a few changes in terms of folder structure and styling dependencies. However, I'll soon be rebasing this back on top of the original kit since it has come along in a couple regards (rebasing remote master?!?! yeah, :joy_cat:, but it needs to be done.).

**Comment by fusionstrings** [comment]
Thanks, I understand but I am not using this entire kit but deriving parts of it as I felt this very neatly written. I just needed help for utility function. I've fallen back on old school reducers for now. 

All the best for new version.
